def add(a,b):
    print('Addition: ',a+b)
def sub(a,b):
    print('Subtraction: ',a-b)
def mul(a,b):
    print('Multiplication: ',a*b)
def div(a,b):
    print('Division: ',a/b)
def exp(a,b):
    print("Exponential: ",a**b)
def rem(a,b):
    print("Remainder: ",a%b)